site_name: Phentrieve Documentation
site_url: https://berntpopp.github.io/phentrieve/
repo_url: https://github.com/berntpopp/phentrieve/
repo_name: Phentrieve on GitHub
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  logo: assets/hpo-logo.svg
  favicon: assets/hpo-logo.svg
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - toc.integrate

nav:
  - 'Home': 'index.md'
  - 'Getting Started':
    - 'Installation': 'getting-started/installation.md'
    - 'Initial Setup': 'getting-started/initial-setup.md'
  - 'User Guide':
    - 'Overview': 'user-guide/index.md'
    - 'CLI Usage': 'user-guide/cli-usage.md'
    - 'Text Processing Guide': 'user-guide/text-processing-guide.md'
    - 'Benchmarking Guide': 'user-guide/benchmarking-guide.md'
    - 'Configuration Profiles': 'user-guide/configuration-profiles.md'
    - 'API Usage': 'user-guide/api-usage.md'
    - 'Frontend Usage': 'user-guide/frontend-usage.md'
  - 'Core Concepts':
    - 'Overview': 'core-concepts/index.md'
    - 'RAG-HPO': 'core-concepts/rag-hpo.md'
    - 'Multilingual Embeddings': 'core-concepts/multilingual-embeddings.md'
    - 'Reranking': 'core-concepts/reranking.md'
    - 'Ontology Similarity': 'core-concepts/ontology-similarity.md'
  - 'Advanced Topics':
    - 'Overview': 'advanced-topics/index.md'
    - 'Text Processing Pipeline': 'advanced-topics/text-processing-pipeline.md'
    - 'Benchmarking Framework': 'advanced-topics/benchmarking-framework.md'
  - 'Deployment':
    - 'Overview': 'deployment/index.md'
    - 'Docker & NPM': 'deployment/docker-npm.md'
    - 'Local Docker': 'deployment/local-docker.md'
    - 'Data Management': 'deployment/data-management.md'
  - 'Development':
    - 'Overview': 'development/index.md'
    - 'Project Structure': 'development/project-structure.md'
    - 'Development Environment': 'development/dev-environment.md'
    - 'Running Tests': 'development/running-tests.md'
  - 'FAQ': 'faq.md'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - glightbox

extra_css:
  - stylesheets/extra.css
