from __future__ import annotations

DEFAULT_LLM_LANGUAGE = "en"
DEFAULT_LLM_MODE = "two_phase"

DEFAULT_PROVIDER_NAME = "gemini"
DEFAULT_PROVIDER_TEMPERATURE = 0.0
DEFAULT_PROVIDER_MAX_TOKENS = 8192
DEFAULT_PROVIDER_TRANSIENT_RETRIES = 3
DEFAULT_PROVIDER_RETRYABLE_STATUS_CODES = (429, 500, 503, 504)
DEFAULT_PROVIDER_RETRY_INITIAL_BACKOFF_SECONDS = 1.0
DEFAULT_PROVIDER_RETRY_BACKOFF_MULTIPLIER = 2.0
DEFAULT_PROVIDER_RETRY_MAX_BACKOFF_SECONDS = 8.0
DEFAULT_PROVIDER_RETRY_JITTER_SECONDS = 0.25
DEFAULT_PROVIDER_STRUCTURED_RETRIES = 1
DEFAULT_PROVIDER_STRUCTURED_RETRY_TOKEN_MULTIPLIER = 2
DEFAULT_PROVIDER_TIMEOUT_SECONDS = 120
DEFAULT_TOOL_QUERY_RESULTS = 10
DEFAULT_PROCESS_CLINICAL_TEXT_NUM_RESULTS_PER_CHUNK = 15
DEFAULT_PROCESS_CLINICAL_TEXT_CHUNK_RETRIEVAL_THRESHOLD = 0.25

DEFAULT_QUERY_RESULTS_PER_PHRASE = 200
DEFAULT_LLM_RETRIEVAL_BATCH_SIZE = 25
DEFAULT_PHASE1_MAX_OUTPUT_TOKENS = DEFAULT_PROVIDER_MAX_TOKENS
DEFAULT_PHASE1_MAX_PHENOTYPES = 128
DEFAULT_SIMILARITY_THRESHOLD = 0.35
DEFAULT_MIN_UNIQUE_CANDIDATES = 15
DEFAULT_MAX_UNIQUE_CANDIDATES = 20
DEFAULT_LOCAL_MATCH_THRESHOLD = 80.0

PROMPT_VARIANT_MAPPING = "mapping"

PRESENT_ASSERTION = "present"
NEGATED_ASSERTION = "negated"
UNCERTAIN_ASSERTION = "uncertain"
